spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/food_ordering_service?serverTimezone=Asia/Seoul
    username: root
    password: 1215

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    show-sql: true
    # hibernate Mysql 설정
    database-platform: org.hibernate.dialect.MySQL8Dialect

    # DB의 고유 기능 사용 가능
    hibernate:
      ddl-auto: update

    # SQL의 가독성 높임(JPA 구현체인 Hibernate 동작)
    properties:
      hibernate.format_sql: true

kakao:
  secret: a7a2f38c20deae484401731c080a2117

jwt:
  access_expiration_time: 360036003600
  refresh_expiration_time: 1209600
  secret: 3ff3e0a7b04deb427e630aa85181956bcdbc46249df88454f0a0731302e0df0b82bd1dcac3852474689d517307bafa63a569cf19fae43c38a21b4706c45b1733