name: jacoco

on:
  pull_request:
    branches:
      - main
      - feature/*


permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set Kakao Secret in Environment Variable
        run: echo "KAKAO_SECRET=${{ secrets.KAKAO_SECRET }}" >> $GITHUB_ENV

      - name: Build with Gradle
        env:
          KAKAO_SECRET: ${{ secrets.KAKAO_SECRET }}
        run: ./gradlew build

      - name: Test with Gradle
        env:
          KAKAO_SECRET: ${{ secrets.KAKAO_SECRET }}
        run: SPRING_PROFILES_ACTIVE=[test] ./gradlew --info test

      - name: Test Coverage Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.6
        with:
          title: "⭐️Code Coverage"
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 70
          min-coverage-changed-files: 70
          update-comment: true



